In [2]:
import torch

In [3]:
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(2, 2)
print(x)

tensor([[0.0721, 0.4973],
        [0.8380, 0.6128]])


In [5]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [6]:
x = torch.ones(2, 2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [7]:
print(x.dtype)

torch.float32


In [8]:
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)

torch.int32


In [9]:
print(x.size())

torch.Size([2, 2])


In [10]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.7081, 0.6547],
        [0.8393, 0.8454]])
tensor([[0.6645, 0.4412],
        [0.8988, 0.0558]])


In [12]:
z = x + y
z = torch.add(x, y)
print(z)

tensor([[1.3726, 1.0959],
        [1.7380, 0.9013]])


In [13]:
y.add_(x) #underscore will have inplace effect
print(y)

tensor([[1.3726, 1.0959],
        [1.7380, 0.9013]])


In [14]:
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.6645, -0.4412],
        [-0.8988, -0.0558]])


In [15]:
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[0.9720, 0.7174],
        [1.4587, 0.7620]])


In [16]:
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.5159, 0.5974],
        [0.4829, 0.9381]])


In [17]:
x = torch.rand(5, 3)
print(x)
print(x[:, 0])

tensor([[0.6765, 0.6245, 0.7338],
        [0.1970, 0.2651, 0.1403],
        [0.5488, 0.7593, 0.5412],
        [0.6542, 0.1341, 0.6446],
        [0.3404, 0.5388, 0.1883]])
tensor([0.6765, 0.1970, 0.5488, 0.6542, 0.3404])


In [19]:
x = torch.rand(4, 4)
print(x)
y = x.view(16)
print(y)

tensor([[0.4499, 0.6857, 0.8734, 0.2881],
        [0.3591, 0.7624, 0.8858, 0.6484],
        [0.1794, 0.0289, 0.5656, 0.5534],
        [0.5615, 0.9622, 0.4294, 0.9359]])
tensor([0.4499, 0.6857, 0.8734, 0.2881, 0.3591, 0.7624, 0.8858, 0.6484, 0.1794,
        0.0289, 0.5656, 0.5534, 0.5615, 0.9622, 0.4294, 0.9359])


In [21]:
y = x.view(-1, 8) #-1 can help to change shape
print(y)
print(y.size())

tensor([[0.4499, 0.6857, 0.8734, 0.2881, 0.3591, 0.7624, 0.8858, 0.6484],
        [0.1794, 0.0289, 0.5656, 0.5534, 0.5615, 0.9622, 0.4294, 0.9359]])
torch.Size([2, 8])


In [22]:
import numpy as np

In [24]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
a.add_(1)
print(a)
print(b)
#They will share the same memory location so have to be careful

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [27]:
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y #perfrom on gpu
    z.numpy() # will return error because numpy only handles cpu tensor
    z = z.to("cpu")

In [29]:
x = torch.ones(5, requires_grad=True) #calculate gradients in the steps
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
